[project]
name = "homelab"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["utils"]

[tool.uv]
package = false

[tool.uv.sources]
utils = { workspace = true }

[tool.uv.workspace]
members = ["utils"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
