config:
  kubernetes:config:
    proxmox:
      node-name: pve
      api-endpoint: https://pve-01.mpagel.de:8006
      api-token:
        envvar: PROXMOX_API_TOKEN__PVE_01__PULUMI
    microk8s:
      master-nodes:
        - name: k8s-dev-master-0
          vmid: 1010
          ipv4-address: 10.0.10.100/24
          cores: 2
          memory_mb_min: 2048
          memory_mb_max: 4096
          root_disk_size_gb: 64
          data_disk_size_gb: 32
      ssh-public-key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIThrWKIoEj20S3DosaiKBRUGA89qe1xz9hch2+VhSGd mpagel@k8s-dev
      vlan_id: 10
      sub-domain: app-dev.mpagel.de
    metallb:
      # renovate: datasource=github-releases packageName=metallb/metallb versioning=semver
      version: 0.15.2
      ipv4-start: 10.0.10.115
      ipv4-end: 10.0.10.120
    cert-manager:
      # renovate: datasource=github-releases packageName=cert-manager/cert-manager versioning=semver
      version: v1.18.1
      acme-email: mike@mpagel.de
    traefik:
      # renovate: datasource=github-releases packageName=traefik/traefik-helm-chart versioning=semver
      version: v36.3.0
    cloudflare:
      api-token:
        envvar: CLOUDFLARE_TOKEN
    csi-driver-smb:
      # renovate: datasource=github-releases packageName=kubernetes-csi/csi-driver-smb versioning=loose
      version: v1.18.0
