[project]
name = "utils"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = ["httpx>=0.28.1", "pulumi>=3.147.0", "pydantic>=2.10.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
