[project]
name = "paperless"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pulumi>=3.147.0",
    "pulumi-kubernetes>=4.21.0",
    "pulumi-random>=4.18.0",
    "pydantic>=2.10.1",
    "jinja2>=3.1.4",
]
