name: Code Quality
on: [push]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync

      - name: pyright
        run: uv run pyright --warnings

      - name: ruff check
        run: uv run ruff check

      - name: ruff format
        run: uv run ruff format --check

      - name: Install Ansible dependencies
        run:
          uv run ansible-galaxy collection install
            -r packages/proxmox/ansible/ansible-requirements.yaml

      - name: Run Ansible Lint
        run: uv run ansible-lint -v
          packages/proxmox/ansible/inventory
          packages/proxmox/ansible/playbooks
          packages/proxmox/ansible/roles
